name: Build GoShort-CLI

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build GoShort-CLI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go 1.22.5
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Run make all
      run: make all

    - name: List build files
      id: list_files
      run: |
        # List all files in the build directory
        find build -type f | tr '\n' ' ' | sed 's/ $//' > files.txt
        cat files.txt

    - name: Upload binaries to release
      run: |
        while read -r file; do
          if [ -f "$file" ]; then
            # Extract platform from the file path
            if [[ "$file" == *"/windows-amd64/"* ]]; then
              platform="windows-amd64"
            elif [[ "$file" == *"/windows-arm64/"* ]]; then
              platform="windows-arm64"
            elif [[ "$file" == *"/linux-amd64/"* ]]; then
              platform="linux-amd64"
            elif [[ "$file" == *"/linux-arm64/"* ]]; then
              platform="linux-arm64"
            elif [[ "$file" == *"/macos-amd64/"* ]]; then
              platform="macos-amd64"
            elif [[ "$file" == *"/macos-arm64/"* ]]; then
              platform="macos-arm64"
            else
              platform="unknown"
            fi
            
            filename=$(basename "$file")
            basepath=$(dirname "$file")
            if [[ "$file" == *.exe ]]; then
              asset_name="${platform}/${filename}"
            else
              asset_name="${platform}/${filename}"
            fi
            
            echo "Uploading $filename as $asset_name..."
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: $(file -b --mime-type "$file")" \
                 --data-binary @"$file" \
                 "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${asset_name}"
          fi
        done < files.txt
