name: Build GoShort-CLI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build GoShort-CLI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go 1.22.5
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Run make all
      run: make all

    - name: List build files
      id: list_files
      run: |
        echo "FILES=$(ls build/**/*.exe build/**/*.gz build/**/* | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Upload binaries to release
      run: |
        for file in ${{ env.FILES }}; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "Uploading $filename..."
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: $(file -b --mime-type $file)" \
                 --data-binary @"$file" \
                 "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$filename"
          fi
        done
