name: Build GoShort-CLI

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build GoShort-CLI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go 1.22.5
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Run make all
      run: make all

    - name: List build files
      id: list_files
      run: |
        find build -type f > files.txt
        cat files.txt

    - name: Upload binaries to release
      run: |
        while IFS= read -r file; do
          if [ -f "$file" ]; then
            case "$file" in
              *"/windows-amd64/"*) platform="windows-amd64" ;;
              *"/windows-arm64/"*) platform="windows-arm64" ;;
              *"/linux-amd64/"*) platform="linux-amd64" ;;
              *"/linux-arm64/"*) platform="linux-arm64" ;;
              *"/macos-amd64/"*) platform="macos-amd64" ;;
              *"/macos-arm64/"*) platform="macos-arm64" ;;
              *) platform="unknown" ;;
            esac

            filename=$(basename "$file")
            basepath=$(dirname "$file")
            if [[ "$filename" == *.exe ]]; then
              asset_name="${platform}/${filename}"
            else
              asset_name="${platform}/${filename}"
            fi
            
            echo "Uploading $file as $asset_name..."
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: $(file -b --mime-type "$file")" \
                 --data-binary @"$file" \
                 "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${asset_name}"
          else
            echo "$file does not exist"
          fi
        done < files.txt
